name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            name: kopfrechner-windows
            content_type: application/zip
            archive: zip
          - target: x86_64-unknown-linux-musl
            name: kopfrechner-linux
            content_type: application/x-gzip
            archive: tar.gz
          - target: x86_64-apple-darwin
            name: kopfrechner-macos
            content_type: application/zip
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: stable
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: ${{ matrix.name }}
          UPLOAD_MODE: none
          MINIFY: true
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          asset_name: ${{ matrix.name }}-${{ github.event.release.tag_name }}.${{ matrix.archive }}
          asset_content_type: ${{ matrix.content_type }}
